name: 'Hello World Docker Action'

description: 'A simple workflow to say hello'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'Time of day we say hello'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}