name: Github Actions Demo

on:
    push:
        branches: [main]
        paths-ignore: [.github/**]
    pull_request:
        branches: [main]
    schedule:
        - cron: '15 6 * * 0'
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to'
                type: environment
                required: true
    
jobs: 
    Build:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "🎉 The job was triggered by event: ${{ github.event_name }}"
                echo "You chose the ${{ inputs.environment }} environment"
                echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
            - uses: actions/checkout@v4

            - name: List files in the repository
              run: |
                echo "The repository ${{ github.repository }} contains the following files:"
                tree
    Test:
        runs-on: ubuntu-latest
        needs: Build
        environment:
            name: test
        steps:
            - run: |
                echo "🎉 The job was triggered by event: ${{ github.event_name }}"
                echo "Testing..."

    Load-Test:
        runs-on: ubuntu-latest
        needs: [Test]
        environment:
            name: load-test
        steps:
            - run: |
                echo "🎉 The job was triggered by event: ${{ github.event_name }}"
                echo "Testing..."
    Production:
        runs-on: ubuntu-latest
        needs: [Test, Load-Test]
        environment:
            name: production
        steps:
            - run: |
                echo "Step 1 Deploying..."
                sleep 10
            - run: |
                echo "Step 2 Deploying..."
                sleep 10
            - run: |
                echo "Step 3 Deploying..."
                sleep 10
            - run: |
                echo "Step 4 Deploying..."
                sleep 10
            - run: |
                echo "Step 5 Deploying..."
                sleep 10
