name: Hello World Docker Action

on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch: 

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run my action
        id: hello-action
        uses: ./hello-world-docker-action
        with: 
          who-to-greet: '@ralphkaram'
      - name: Display Time
        run: echo "The time fo day is ${{ steps.hello-action.output-time }} when the action said hello"
